modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "emi"
mandatory = true
versionRange = "[1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "emibridge"
mandatory = true
versionRange = "[1.0-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "industrialforegoing"
mandatory = true
versionRange = "[1.21-3.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = false
versionRange = "[19,)"
ordering = "NONE"
side = "BOTH"
